<template>
  <div class="container has-text-centered">
    <section class="section">
      <h1 class="is-size-3 has-margin-bottom-3">
        Privacy Policy
      </h1>
    </section>
    <section class="paragraph">
      Effective date: 02/20/2020
    </section>
    <section class="paragraph">
      <h3>1. Introduction</h3>
      <p>
        Welcome to <span class="has-text-weight-bold">Qtorial.</span>
        Qtorial (hereinafter referred to as “<span class="has-text-weight-bold">us</span>”, “<span class="has-text-weight-bold">we</span>”, or “<span class="has-text-weight-bold">our</span>”) operates web pages located at
        <a href="https://q-torial.app" target="_blank">https://q-torial.app</a> and related browser extensions (hereinafter referred to as “<span class="has-text-weight-bold">Service</span>”).<br />
        Our Privacy Policy governs your visit to https://q-torial.app, and explains how we collect, safeguard, and disclose information that results from your use of our Service.<br />
        We use your data to provide and improve the Service. By using our Service, you agree to the collection and use of information in accordance with this policy.<br />
        Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.<br />
        Our Terms and Conditions (“<span class="has-text-weight-bold">Terms</span>”) govern all use of our Service and together with the Privacy<br />
        Policy constitutes your agreement with us (“<span class="has-text-weight-bold">Agreement</span>”).
      </p>
    </section>
    <section class="paragraph">
      <h3>2. Definitions</h3>
      <div>
        <p class="has-margin-bottom-3">
          <span class="has-text-weight-bold">SERVICE</span> means the https://q-torial.app website operated by Qtorial.
        </p>
        <p class="has-margin-bottom-3">
          <span class="has-text-weight-bold">PERSONAL DATA</span> means data about a living individual who can be identified from that data (or from that and other information either in our possession or likely to come into our possession).
        </p>
        <p class="has-margin-bottom-3">
          <span class="has-text-weight-bold">USAGE DATA</span> is data collected automatically either generated by the use of our Service or from the Service infrastructure itself (for example, the duration of a page visit).
        </p>
        <p class="has-margin-bottom-3">
          <span class="has-text-weight-bold">COOKIES</span> are small files stored on your device (computer or mobile device).
        </p>
        <p class="has-margin-bottom-3">
          <span class="has-text-weight-bold">DATA CONTROLLER</span> means a natural or legal person who (either alone or jointly, or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.<br />
          For the purpose of this Privacy Policy, we are a Data Controller of your data.
        </p>
        <p class="has-margin-bottom-3">
          <span class="has-text-weight-bold">DATA PROCESSORS (OR SERVICE PROVIDERS)</span>
          means any natural or legal person who processes the data on behalf of the Data Controller.<br />
          We may use the services of various Service Providers in order to process your data more effectively.
        </p>
        <p class="has-margin-bottom-3">
          <span class="has-text-weight-bold">DATA SUBJECT</span>
          is any living individual who is the subject of Personal Data.
        </p>
        <p class="has-margin-bottom-3">
          <span class="has-text-weight-bold">THE USER</span>
          is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
        </p>
      </div>
    </section>
    <section class="paragraph">
      <h3>3. Information Collection and Use</h3>
      <p>
        We collect several different types of information for various purposes to provide and improve our Service to you.
      </p>
    </section>
    <section class="paragraph">
      <h3>4. Types of Data Collected</h3>
      <p>
        <div class="has-margin-bottom-3">
          <span class="has-text-weight-bold">Personal Data</span>
          <p class="has-margin-top-3">
          While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“<span class="has-text-weight-bold">Personal Data</span>”).<br />
          Personally identifiable information may include, but is not limited to:
          </p>
            <ol style="list-style-type: lower-alpha">
              <li>Email address</li>
              <li>Cookies and Usage Data</li>
            </ol>
          <p>
          We may use your Personal Data to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. <br />
          You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at support@q-torial.app.
          </p>
        </div>
        <div class="has-margin-bottom-3">
          <span class="has-text-weight-bold">Usage Data</span>
          <p class="has-margin-top-3">
          We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device (“<span class="has-text-weight-bold">Usage Data</span>”).<br />
          This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.<br />
          When you access our Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, , the type of mobile Internet browser you use, unique device identifiers, and other diagnostic data.
          </p>
        </div>
        <div class="has-margin-bottom-3">
          <span class="has-text-weight-bold">Tracking Cookies Data</span>
          <p class="has-margin-top-3">
          We use cookies and similar tracking technologies to track the activity on our Service, and we hold certain information.<br />
          Cookies are files with a small amount of data which may include an anonymous unique identifier.<br />
          Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service.<br />
          You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.<br />
          However, if you do not accept cookies, you may not be able to use some portions of our Service.<br />
          Examples of Cookies we use:
          </p>
          <ol style="list-style-type: lower-alpha">
            <li>Session Cookies: We use Session Cookies to operate our Service.</li>
            <li>Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</li>
            <li>Security Cookies: We use Security Cookies for security purposes.</li>
            <li>Advertising Cookies: Advertising Cookies are used to serve you with advertisements that
              may be relevant to you and your interests.</li>
          </ol>
      </div>
    </section>
    <section class="paragraph">
      <h3>5. Use of Data</h3>
      <p>
        Qtorial uses the collected data for various purposes:
        <ol style="list-style-type: lower-alpha">
          <li>to provide and maintain our Service;</li>
          <li>to notify you about changes to our Service;</li>
          <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
          <li>to provide customer support;</li>
          <li>to gather analysis or valuable information so that we can improve our Service;</li>
          <li>to monitor the usage of our Service;</li>
          <li>to detect, prevent, and address technical issues;</li>
          <li>to fulfill any other purpose for which you provide it;</li>
          <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
          <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
          <li>to provide you with news, special offers, and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
          <li>in any other way we may describe when you provide the information;</li>
          <li>for any other purpose with your consent.</li>
        </ol>
      </p>
    </section>
    <section class="paragraph">
      <h3>6. Retention of Data</h3>
      <p>
        We will retain your Personal Data only for as long as is necessary for the purposes set out in this
        Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your data to comply with applicable
        laws), resolve disputes, and enforce our legal agreements and policies.<br />
        We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for
        a shorter period, except when this data is used to strengthen the security or to improve the
        functionality of our Service, or we are legally obligated to retain this data for longer time periods.
      </p>
    </section>
    <section class="paragraph">
      <h3>7. Transfer of Data</h3>
      <p>
        Your information, including Personal Data, may be transferred to – and maintained on – computers
        located outside of your state, province, country or other governmental jurisdiction where the data
        protection laws may differ from those of your jurisdiction.
        Your consent to this Privacy Policy followed by your submission of such information represents your
        agreement to that transfer.<br />
        Qtorial will take all the steps reasonably necessary to ensure that your data is treated securely and
        in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an
        organization or a country unless there are adequate controls in place including the security of your
        data and other personal information.
      </p>
    </section>
    <section class="paragraph">
      <h3>8. Disclosure of Data</h3>
      <p>
        We may disclose personal information that we collect, or you provide:
      </p>
      <ol style="list-style-type: lower-alpha">
        <li>
          <span class="has-text-weight-bold is-block">Disclosure for Law Enforcement.</span>
          Under certain circumstances, we may be required to disclose your Personal Data if required
          to do so by law or in response to valid requests by public authorities.</li>
        <li>
          <span class="has-text-weight-bold is-block">Business Transaction.</span>
          If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal
          Data may be transferred.</li>
        <li>
          <span class="has-text-weight-bold is-block">Other cases. </span>
          We may disclose your information also to our subsidiaries and affiliates.
        </li>
      </ol>
      </p>
    </section>
    <section class="paragraph">
      <h3>9. Security of Data</h3>
      <p>
        The security of your data is important to us, but remember that no method of transmission over the
        Internet or method of electronic storage is 100% secure. While we strive to use commercially
        acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
      </p>
    </section>
    <section class="paragraph">
      <h3>10. Service Providers</h3>
      <p>
        We may employ third party companies and individuals to facilitate our Service (“<span class="has-text-weight-bold">Service
        Providers</span>”), provide amenities on our behalf, perform business-related services, or assist us in
        analyzing how our Service is used.<br/>
        These third parties have access to your Personal Data only to perform these tasks on our behalf
        and are obligated not to disclose or use it for any other purpose.
      </p>
    </section>
    <section class="paragraph">
      <h3>11. Analytics</h3>
      <div>
        <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
        <div class="has-margin-y-3">
          <span class="has-text-weight-bold">Google Analytics</span>
          <p class="has-margin-top-3">
            Google Analytics is a web analytics service offered by Google that tracks and reports
            website traffic. Google uses the data collected to track and monitor the use of our Service.
            This data is shared with other Google services. Google may use the collected data to
            contextualize and personalize the ads of its own advertising network.<br />
            For more information on the privacy practices of Google, please visit the Google Privacy
            Terms web page: https://policies.google.com/privacy?hl=en<br />
            We also encourage you to review Google's policy for safeguarding your data:
            https://support.google.com/analytics/answer/6004245.
          </p>
        </div>
        <div class="has-margin-y-3">
          <span class="has-text-weight-bold">Firebase</span>
          <p class="has-margin-top-3">
            Firebase is an analytics service provided by Google Inc.<br />
            You may opt-out of certain Firebase features through your mobile device settings, such as
            your device’s advertising settings or by following the instructions provided by Google in their
            Privacy Policy: https://policies.google.com/privacy?hl=en<br />
            For more information on what type of information Firebase collects, please visit the Google
            Privacy Terms web page: https://policies.google.com/privacy?hl=en
          </p>
        </div>
      </div>
    </section>
    <section class="paragraph">
      <h3>12. CI/CD tools</h3>
      <div>
        <p>We may use third-party Service Providers to automate the development process of our Service.</p>
        <div class="has-margin-y-3">
          <span class="has-text-weight-bold">GitHub</span>
          <p class="has-margin-top-3">
            GitHub is provided by GitHub, Inc.<br />
            GitHub is a development platform to host and review code, manage projects, and build
            software.<br />
            For more information on what data GitHub collects for what purpose and how the protection
            of the data is ensured, please visit the GitHub Privacy Policy page:
            https://help.github.com/en/articles/github-privacy-statement.
          </p>
        </div>
        <div class="has-margin-y-3">
          <span class="has-text-weight-bold">CircleCI</span>
          <p class="has-margin-top-3">
            CircleCI is provided by Circle Internet Services, Inc.<br />
            CircleCI is Continuous Integration, a development practice which is being used by software
            teams allowing them to build, test and deploy applications easier and quicker on multiple
            platforms.<br />
            For more information on what data Circle CI collects for what purpose and how the
            protection of the data is ensured, please visit the Circle CI Privacy Policy page:
            https://circleci.com/privacy/.
          </p>
        </div>
      </div>
    </section>
    <section class="paragraph">
      <h3>13. Payments</h3>
      <div>
        <p>
          We may provide paid products and/or services within our Service. In that case, we use third-party
          services for payment processing (e.g. payment processors).<br />
          We will not store or collect your payment card details - that information is provided directly to our
          third-party payment processors whose use of your personal information is governed by their Privacy
          Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI
          Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American
          Express and Discover. PCI-DSS requirements help ensure the secure handling of payment
          information.<br />The payment processors we work with are:
        </p>
        <div class="has-margin-y-3">
          <span class="has-text-weight-bold">Stripe</span>
          <p class="has-margin-top-3">
            Their Privacy Policy can be viewed at: https://stripe.com/us/privacy
          </p>
        </div>
      </div>
      </section>
    <section class="paragraph">
      <h3>14. Links to Other Sites</h3>
        <p>
          Our Service may contain links to other sites that are not operated by us. If you click a third party
          link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy
          of every site you visit.
          We have no control over and assume no responsibility for the content, privacy policies, or practices
          of any third party sites or services
        </p>
      </section>
      <section class="paragraph">
        <h3>15. Children's Privacy</h3>
        <p>
          Our Services are not intended for use by children under the age of 18 (“<span class="has-text-weight-bold">Child</span>” or “<span class="has-text-weight-bold">Children</span>”).
          We do not knowingly collect personally identifiable information from Children under 18. If you
          become aware that a Child has provided us with Personal Data, please contact us. If we become
          aware that we have collected Personal Data from Children without verification of parental consent,
          we take steps to remove that information from our servers.
        </p>
      </section>
      <section class="paragraph">
        <h3>16. Changes to This Privacy Policy</h3>
        <p>
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting
          the new Privacy Policy on this page.<br />
          We will let you know via email and/or a prominent notice on our Service, prior to the change
          becoming effective and update “effective date” at the top of this Privacy Policy.<br />
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy
          Policy are effective when they are posted on this page.
        </p>
      </section>
      <section class="paragraph">
        <h3>17. Contact Us</h3>
        <p>
          If you have any questions about this Privacy Policy, please contact us: By email: support@q-torial.app
        </p>
      </section>
    <the-footer />
  </div>
</template>

<script>

import BaseLevel from '../../atoms/BaseLevel';
import BaseLevelItem from '../../atoms/BaseLevelItem';
import TheFooter from '../../organisms/global/TheFooter/TheFooter';

export default {
  name: 'PrivacyPolicyPage',
  components: {
    TheFooter,
  },
};
</script>

<style scoped>
  .paragraph {
    text-align: left;
    margin-bottom: 25px;
  }
  .paragraph > h3 {
    font-size: 1.3em;
    font-weight: bold;
    margin-bottom: 25px;
  }
  .paragraph > p {
    width: 100%;
    max-width: 100%;
  }
  .paragraph ol, .paragraph ul {
    margin-left: 0;
    padding-left: 40px;
  }
</style>
