// ./index
export const SET_USER = 'SET_USER';
export const SET_ERROR_CODE = 'SET_ERROR_CODE';
export const SET_SERVER_SIDE_ERRORS = 'SET_SERVER_SIDE_ERRORS';

export const UPDATE_AUTH = 'UPDATE_AUTH';

export const UPDATE_GOOGLE_ANALYTICS = 'UPDATE_GOOGLE_ANALYTICS';
export const LIST_GOOGLE_ANALYTICS = 'LIST_GOOGLE_ANALYTICS';

export const SET_ALL_FETCHED = 'SET_ALL_FETCHED';
export const SET_REQUESTING = 'SET_REQUESTING';
export const UPDATE_ORDER_BY = 'UPDATE_ORDER_BY';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';

export const ADD_TUTORIAL = 'ADD_TUTORIAL';
export const UPDATE_TUTORIAL = 'UPDATE_TUTORIAL';
export const DELETE_TUTORIAL = 'DELETE_TUTORIAL';
export const SELECT_TUTORIAL = 'SELECT_TUTORIAL';
export const SORT_TUTORIALS = 'SORT_TUTORIALS';

export const SELECT_GA = 'SELECT_GA';
export const SORT_GAS = 'SORT_GAS';
export const ADD_GA = 'ADD_GA';
export const UPDATE_GA = 'UPDATE_GA';
export const DELETE_GA = 'DELETE_GA';
export const SET_GA_ACCOUNTS = 'SET_GA_ACCOUNTS';

export const SET_PERFORMANCE = 'SET_PERFORMANCE';
