// ./index
export const SET_USER = 'SET_USER';
export const SET_ERROR_CODE = 'SET_ERROR_CODE';
export const SET_SERVER_SIDE_ERRORS = 'SET_SERVER_SIDE_ERRORS';

export const UPDATE_AUTH = 'UPDATE_AUTH';
export const DELETE_OAUTH = 'DELETE_OAUTH';
export const UPDATE_GOOGLE_ANALYTICS = 'UPDATE_GOOGLE_ANALYTICS';
export const LIST_GOOGLE_ANALYTICS = 'LIST_GOOGLE_ANALYTICS';

export const SELECT_TUTORIAL = 'SELECT_TUTORIAL';
export const SET_ALL_FETCHED = 'SET_ALL_FETCHED';
export const SET_REQUESTING = 'SET_REQUESTING';
export const UPDATE_ORDER_BY = 'UPDATE_ORDER_BY';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const SORT_TUTORIALS = 'SORT_TUTORIALS';
